import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1766507414034 implements MigrationInterface {
    name = 'InitSchema1766507414034'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`test_cases\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`inputData\` longtext NOT NULL, \`expectedOutput\` longtext NULL, \`time_limit_ms\` int NOT NULL, \`memory_limit_kb\` int NOT NULL, \`is_hidden\` tinyint NOT NULL DEFAULT 1, \`hash\` varchar(64) NULL, \`order_no\` int NULL, \`test_group_id\` bigint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`test_groups\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`name\` varchar(255) NULL, \`order_no\` int NULL, \`points\` int NOT NULL DEFAULT '0', \`is_sample\` tinyint NOT NULL DEFAULT 0, \`problem_version_id\` bigint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`problem_hints\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`step_no\` int NOT NULL, \`contentMd\` longtext NOT NULL, \`problem_version_id\` bigint NULL, UNIQUE INDEX \`IDX_ae435edbf4bc54895757ad0c05\` (\`problem_version_id\`, \`step_no\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`problem_examples\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`order_no\` int NOT NULL, \`inputText\` longtext NOT NULL, \`outputText\` longtext NOT NULL, \`explanationMd\` longtext NULL, \`problem_version_id\` bigint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`problem_statements\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`title\` varchar(255) NOT NULL, \`descriptionMd\` longtext NOT NULL, \`inputSpecMd\` longtext NULL, \`outputSpecMd\` longtext NULL, \`constraintsMd\` longtext NULL, \`notesMd\` longtext NULL, \`problem_version_id\` bigint NULL, \`language_id\` bigint NULL, UNIQUE INDEX \`IDX_5d115f32b62761364140215c20\` (\`problem_version_id\`, \`language_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`password_reset_tokens\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`token_hash\` varchar(255) NOT NULL, \`expires_at\` datetime NOT NULL, \`used_at\` datetime NULL, \`user_id\` bigint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`oauth_providers\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`code\` varchar(50) NOT NULL, UNIQUE INDEX \`IDX_edb8eb7b21dfcf168d3e2fd5ea\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_oauth_accounts\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`provider_user_id\` varchar(255) NOT NULL, \`access_token\` text NULL, \`refresh_token\` text NULL, \`user_id\` bigint NULL, \`provider_id\` bigint NULL, UNIQUE INDEX \`IDX_826b133c0546f9b9cd118b4948\` (\`provider_id\`, \`provider_user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_sessions\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`refresh_token_hash\` varchar(255) NOT NULL, \`ip\` varchar(45) NULL, \`user_agent\` varchar(255) NULL, \`expires_at\` datetime NOT NULL, \`revoked_at\` datetime NULL, \`user_id\` bigint NULL, INDEX \`idx_user_sessions_user\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`code\` varchar(50) NOT NULL, UNIQUE INDEX \`IDX_f6d54f95c31b73fb1bdd8e91d0\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_profiles\` (\`user_id\` bigint NOT NULL, \`avatar_url\` varchar(500) NULL, \`bio\` text NULL, \`experience_points\` int NOT NULL DEFAULT '0', \`level\` int NOT NULL DEFAULT '1', PRIMARY KEY (\`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`email\` varchar(255) NULL, \`username\` varchar(100) NOT NULL, \`password_hash\` varchar(255) NULL, \`status\` enum ('active', 'banned', 'deleted') NOT NULL DEFAULT 'active', \`country_code\` varchar(2) NULL, \`last_login_at\` datetime NULL, UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`topics\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`slug\` varchar(100) NULL, \`name\` varchar(100) NOT NULL, UNIQUE INDEX \`IDX_97c66ab0029f49fde30517f819\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`problem_topics\` (\`problem_id\` bigint NOT NULL, \`topic_id\` bigint NOT NULL, PRIMARY KEY (\`problem_id\`, \`topic_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`companies\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`slug\` varchar(100) NULL, \`name\` varchar(100) NOT NULL, UNIQUE INDEX \`IDX_b28b07d25e4324eee577de5496\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`problem_companies\` (\`problem_id\` bigint NOT NULL, \`company_id\` bigint NOT NULL, PRIMARY KEY (\`problem_id\`, \`company_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tags\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`slug\` varchar(100) NULL, \`name\` varchar(100) NOT NULL, UNIQUE INDEX \`IDX_b3aa10c29ea4e61a830362bd25\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`problem_tags\` (\`problem_id\` bigint NOT NULL, \`tag_id\` bigint NOT NULL, PRIMARY KEY (\`problem_id\`, \`tag_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`problems\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`code\` varchar(150) NOT NULL, \`difficulty\` enum ('easy', 'medium', 'hard') NOT NULL, \`status\` enum ('draft', 'published', 'archived') NOT NULL DEFAULT 'draft', \`created_by\` bigint NOT NULL, UNIQUE INDEX \`IDX_92cf8d938405ef6369f311f0c4\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`problem_versions\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`version_no\` int NOT NULL, \`changeLog\` text NULL, \`isActive\` tinyint NOT NULL DEFAULT 0, \`problem_id\` bigint NULL, \`created_by\` bigint NOT NULL, UNIQUE INDEX \`IDX_78886d6bb133f882cd17cf0ae0\` (\`problem_id\`, \`version_no\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`problem_checkers\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`checkerType\` enum ('default', 'custom') NOT NULL, \`sourceCode\` longtext NULL, \`problem_version_id\` bigint NULL, \`language_id\` bigint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`languages\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`code\` varchar(10) NOT NULL, \`name\` varchar(50) NOT NULL, UNIQUE INDEX \`IDX_7397752718d1c9eb873722ec9b\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`badges\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`code\` varchar(100) NOT NULL, \`name\` varchar(100) NOT NULL, \`description\` text NULL, \`icon_url\` varchar(255) NULL, UNIQUE INDEX \`IDX_48fe47e292737e09162b08c4f7\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_badges\` (\`user_id\` bigint NOT NULL, \`badge_id\` bigint NOT NULL, \`earned_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`user_id\`, \`badge_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`skills\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`name\` varchar(100) NOT NULL, UNIQUE INDEX \`IDX_81f05095507fd84aa2769b4a52\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_skills\` (\`user_id\` bigint NOT NULL, \`skill_id\` bigint NOT NULL, \`level\` tinyint NULL, \`years\` tinyint NULL, PRIMARY KEY (\`user_id\`, \`skill_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_problem_stats\` (\`user_id\` bigint NOT NULL, \`problem_id\` bigint NOT NULL, \`bestStatus\` enum ('unsolved', 'attempted', 'solved') NOT NULL, \`best_runtime_ms\` int NULL, \`best_memory_kb\` int NULL, \`first_solved_at\` datetime NULL, \`last_attempt_at\` datetime NULL, PRIMARY KEY (\`user_id\`, \`problem_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`code_drafts\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`sourceCode\` longtext NOT NULL, \`user_id\` bigint NULL, \`problem_id\` bigint NULL, \`language_id\` bigint NOT NULL, UNIQUE INDEX \`IDX_bfb5b81c1911e9be2b198594df\` (\`user_id\`, \`problem_id\`, \`language_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`code_runs\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`sourceCode\` longtext NOT NULL, \`stdin\` longtext NULL, \`status\` enum ('queued', 'running', 'finished', 'error') NOT NULL, \`time_ms\` int NULL, \`memory_kb\` int NULL, \`stdout\` longtext NULL, \`stderr\` longtext NULL, \`user_id\` bigint NOT NULL, \`problem_version_id\` bigint NOT NULL, \`language_id\` bigint NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`programming_languages\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`code\` varchar(20) NOT NULL, \`name\` varchar(50) NOT NULL, \`compileCommandTpl\` text NULL, \`runCommandTpl\` text NULL, \`isEnabled\` tinyint NOT NULL DEFAULT 1, UNIQUE INDEX \`IDX_b27c191484858fdadc253e8828\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`judge_jobs\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`queueStatus\` enum ('queued', 'picked', 'done', 'failed', 'retrying') NOT NULL, \`attempt\` int NOT NULL DEFAULT '0', \`worker_id\` varchar(100) NULL, \`started_at\` datetime NULL, \`finished_at\` datetime NULL, \`submission_id\` bigint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`submissions\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`sourceCode\` longtext NOT NULL, \`status\` enum ('queued', 'judging', 'accepted', 'wrong_answer', 'tle', 'mle', 'runtime_error', 'compile_error', 'internal_error') NOT NULL, \`score\` int NOT NULL DEFAULT '0', \`runtime_ms\` int NULL, \`memory_kb\` int NULL, \`user_id\` bigint NOT NULL, \`problem_version_id\` bigint NOT NULL, \`language_id\` bigint NOT NULL, INDEX \`idx_submissions_problem\` (\`problem_version_id\`), INDEX \`idx_submissions_user\` (\`user_id\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`submission_testcase_results\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`status\` enum ('accepted', 'wrong_answer', 'tle', 'mle', 'runtime_error', 'skipped') NOT NULL, \`time_ms\` int NULL, \`memory_kb\` int NULL, \`outputPreview\` text NULL, \`submission_id\` bigint NULL, \`test_case_id\` bigint NOT NULL, UNIQUE INDEX \`IDX_201cd5b8bd6e678a05de0aafe2\` (\`submission_id\`, \`test_case_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`post_votes\` (\`post_id\` bigint NOT NULL, \`user_id\` bigint NOT NULL, \`vote\` tinyint NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`post_id\`, \`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`discussion_posts\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`contentMd\` longtext NOT NULL, \`postType\` enum ('question', 'discussion', 'solution') NOT NULL, \`is_best_solution\` tinyint NOT NULL DEFAULT 0, \`thread_id\` bigint NULL, \`parent_post_id\` bigint NULL, \`author_id\` bigint NOT NULL, \`solution_language_id\` bigint NULL, INDEX \`idx_thread_time\` (\`thread_id\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`discussion_threads\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`title\` varchar(255) NULL, \`is_locked\` tinyint NOT NULL DEFAULT 0, \`problem_id\` bigint NOT NULL, \`created_by\` bigint NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contest_problems\` (\`contest_id\` bigint NOT NULL, \`problem_version_id\` bigint NOT NULL, \`order_no\` int NULL, \`base_points\` int NULL, \`penalty_per_wrong\` int NULL, PRIMARY KEY (\`contest_id\`, \`problem_version_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contest_participants\` (\`contest_id\` bigint NOT NULL, \`user_id\` bigint NOT NULL, \`joined_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`virtual_start_at\` datetime NULL, \`virtual_end_at\` datetime NULL, PRIMARY KEY (\`contest_id\`, \`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contests\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`code\` varchar(100) NOT NULL, \`name\` varchar(255) NOT NULL, \`start_at\` datetime NULL, \`end_at\` datetime NULL, \`type\` enum ('live', 'virtual') NOT NULL, \`is_rated\` tinyint NOT NULL DEFAULT 0, \`created_by\` bigint NULL, UNIQUE INDEX \`IDX_b4731dd3cabd0b2386b443e2e6\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contest_submissions\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`submitted_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`contest_id\` bigint NOT NULL, \`user_id\` bigint NOT NULL, \`submission_id\` bigint NOT NULL, \`problem_version_id\` bigint NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`problem_analytics_daily\` (\`problem_id\` bigint NOT NULL, \`date\` date NOT NULL, \`submissions\` int NOT NULL DEFAULT '0', \`accepted\` int NOT NULL DEFAULT '0', \`unique_users\` int NOT NULL DEFAULT '0', \`avg_runtime_ms\` int NULL, \`avg_memory_kb\` int NULL, PRIMARY KEY (\`problem_id\`, \`date\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`audit_logs\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`action\` varchar(100) NULL, \`target_type\` varchar(100) NULL, \`target_id\` bigint UNSIGNED NULL, \`metadata_json\` json NULL, \`actor_user_id\` bigint NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_roles\` (\`user_id\` bigint NOT NULL, \`role_id\` bigint NOT NULL, INDEX \`IDX_87b8888186ca9769c960e92687\` (\`user_id\`), INDEX \`IDX_b23c65e50a758245a33ee35fda\` (\`role_id\`), PRIMARY KEY (\`user_id\`, \`role_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`test_cases\` ADD CONSTRAINT \`FK_d8c857a3c73908c4e8dbd5125f8\` FOREIGN KEY (\`test_group_id\`) REFERENCES \`test_groups\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test_groups\` ADD CONSTRAINT \`FK_70ead889490b83882a744ecff97\` FOREIGN KEY (\`problem_version_id\`) REFERENCES \`problem_versions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_hints\` ADD CONSTRAINT \`FK_63bfc34bae0e97ed6a7455ce693\` FOREIGN KEY (\`problem_version_id\`) REFERENCES \`problem_versions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_examples\` ADD CONSTRAINT \`FK_dcba451585d017a79af3441b974\` FOREIGN KEY (\`problem_version_id\`) REFERENCES \`problem_versions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_statements\` ADD CONSTRAINT \`FK_6b83ed82bb1eb4085aa8d3a01a5\` FOREIGN KEY (\`problem_version_id\`) REFERENCES \`problem_versions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_statements\` ADD CONSTRAINT \`FK_4908bdeec65b3df8556b12cb307\` FOREIGN KEY (\`language_id\`) REFERENCES \`languages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`password_reset_tokens\` ADD CONSTRAINT \`FK_52ac39dd8a28730c63aeb428c9c\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_oauth_accounts\` ADD CONSTRAINT \`FK_a093a39110ecd3602d87f0e814b\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_oauth_accounts\` ADD CONSTRAINT \`FK_7eb25183e951b6ca44f292df21a\` FOREIGN KEY (\`provider_id\`) REFERENCES \`oauth_providers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` ADD CONSTRAINT \`FK_e9658e959c490b0a634dfc54783\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_profiles\` ADD CONSTRAINT \`FK_6ca9503d77ae39b4b5a6cc3ba88\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_topics\` ADD CONSTRAINT \`FK_04c2262bcf0279527e7c1ce7ac0\` FOREIGN KEY (\`problem_id\`) REFERENCES \`problems\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_topics\` ADD CONSTRAINT \`FK_b3c36df89b28f1046fdfd739e43\` FOREIGN KEY (\`topic_id\`) REFERENCES \`topics\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_companies\` ADD CONSTRAINT \`FK_36f3b2eb80862d2d435920f8d6c\` FOREIGN KEY (\`problem_id\`) REFERENCES \`problems\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_companies\` ADD CONSTRAINT \`FK_ec1e9bbb0e351a047bd25b3b8cc\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_tags\` ADD CONSTRAINT \`FK_e369a453fb95b878301184caddc\` FOREIGN KEY (\`problem_id\`) REFERENCES \`problems\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_tags\` ADD CONSTRAINT \`FK_853473f54d7b1e91b236346fa13\` FOREIGN KEY (\`tag_id\`) REFERENCES \`tags\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problems\` ADD CONSTRAINT \`FK_2aee58a468d036cc139963ae789\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_versions\` ADD CONSTRAINT \`FK_cf1ddcf55381e40759f46e0087d\` FOREIGN KEY (\`problem_id\`) REFERENCES \`problems\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_versions\` ADD CONSTRAINT \`FK_87a7910747c4da573295fea59d1\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_checkers\` ADD CONSTRAINT \`FK_cee7a29419bc1301bec1699bf62\` FOREIGN KEY (\`problem_version_id\`) REFERENCES \`problem_versions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_checkers\` ADD CONSTRAINT \`FK_380eb75ea1990d3f31dd0e0be96\` FOREIGN KEY (\`language_id\`) REFERENCES \`languages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_badges\` ADD CONSTRAINT \`FK_f1221d9b1aaa64b1f3c98ed46d3\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_badges\` ADD CONSTRAINT \`FK_715b81e610ab276ff6603cfc8e8\` FOREIGN KEY (\`badge_id\`) REFERENCES \`badges\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_skills\` ADD CONSTRAINT \`FK_6926002c360291df66bb2c5fdeb\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_skills\` ADD CONSTRAINT \`FK_eb69710b0a00f42fb95fc2ac2f5\` FOREIGN KEY (\`skill_id\`) REFERENCES \`skills\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_problem_stats\` ADD CONSTRAINT \`FK_01ff3887bfd3528d8e61904cfdb\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_problem_stats\` ADD CONSTRAINT \`FK_34f4955f05e2bfaee8969b7d2ae\` FOREIGN KEY (\`problem_id\`) REFERENCES \`problems\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`code_drafts\` ADD CONSTRAINT \`FK_ab119cc7cddc270aa1bde7a118f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`code_drafts\` ADD CONSTRAINT \`FK_7779820de4c13efd6ddcd8fcf01\` FOREIGN KEY (\`problem_id\`) REFERENCES \`problems\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`code_drafts\` ADD CONSTRAINT \`FK_82863e10839b30ece57ef27344a\` FOREIGN KEY (\`language_id\`) REFERENCES \`programming_languages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`code_runs\` ADD CONSTRAINT \`FK_7d8b87357119fe38371ec1e4936\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`code_runs\` ADD CONSTRAINT \`FK_d07e1f5cb7df8f117fe6eeade7d\` FOREIGN KEY (\`problem_version_id\`) REFERENCES \`problem_versions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`code_runs\` ADD CONSTRAINT \`FK_0b1d0cf3df0e3d497fd5bcff7d3\` FOREIGN KEY (\`language_id\`) REFERENCES \`programming_languages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`judge_jobs\` ADD CONSTRAINT \`FK_f7bc8317fbd6d64e81c82d4cd10\` FOREIGN KEY (\`submission_id\`) REFERENCES \`submissions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`submissions\` ADD CONSTRAINT \`FK_fca12c4ddd646dea4572c6815a9\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`submissions\` ADD CONSTRAINT \`FK_2408840ce2806c5d5e072a2e9b4\` FOREIGN KEY (\`problem_version_id\`) REFERENCES \`problem_versions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`submissions\` ADD CONSTRAINT \`FK_f6da7d4c4fa4e0d9db7e5388dd1\` FOREIGN KEY (\`language_id\`) REFERENCES \`programming_languages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`submission_testcase_results\` ADD CONSTRAINT \`FK_c4b6a8ad3128e26008c5894de1c\` FOREIGN KEY (\`submission_id\`) REFERENCES \`submissions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`submission_testcase_results\` ADD CONSTRAINT \`FK_6527eff7f51c75b4a76eb0811e5\` FOREIGN KEY (\`test_case_id\`) REFERENCES \`test_cases\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_votes\` ADD CONSTRAINT \`FK_be565a04e47c8b846f6cc7fcac6\` FOREIGN KEY (\`post_id\`) REFERENCES \`discussion_posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_votes\` ADD CONSTRAINT \`FK_37fb39fa2d813582024968ef264\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`discussion_posts\` ADD CONSTRAINT \`FK_0b0950535a2571b4f375db7b4ae\` FOREIGN KEY (\`thread_id\`) REFERENCES \`discussion_threads\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`discussion_posts\` ADD CONSTRAINT \`FK_f2c4196101d6a0e8d868ad00595\` FOREIGN KEY (\`parent_post_id\`) REFERENCES \`discussion_posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`discussion_posts\` ADD CONSTRAINT \`FK_5861d03c3859af8f7b40032ef08\` FOREIGN KEY (\`author_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`discussion_posts\` ADD CONSTRAINT \`FK_b7185cf357c3d27c3c5b80fec67\` FOREIGN KEY (\`solution_language_id\`) REFERENCES \`programming_languages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`discussion_threads\` ADD CONSTRAINT \`FK_285bbbc4b69b202f169f037d0d6\` FOREIGN KEY (\`problem_id\`) REFERENCES \`problems\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`discussion_threads\` ADD CONSTRAINT \`FK_5fd7e7307b43ad51457114fecb0\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contest_problems\` ADD CONSTRAINT \`FK_2b057cbe0ad987487ad746e6ea7\` FOREIGN KEY (\`contest_id\`) REFERENCES \`contests\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contest_problems\` ADD CONSTRAINT \`FK_79cff0de5c2e9689c9051bfa573\` FOREIGN KEY (\`problem_version_id\`) REFERENCES \`problem_versions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contest_participants\` ADD CONSTRAINT \`FK_070b6a54501fe8b00564f612c0e\` FOREIGN KEY (\`contest_id\`) REFERENCES \`contests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contest_participants\` ADD CONSTRAINT \`FK_005a4088e1f40bae55d74f48069\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contests\` ADD CONSTRAINT \`FK_9a102ffa211c38589ad61786ca7\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contest_submissions\` ADD CONSTRAINT \`FK_cdedd241911ab85d4810cdf6120\` FOREIGN KEY (\`contest_id\`) REFERENCES \`contests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contest_submissions\` ADD CONSTRAINT \`FK_1eb6afc5d255f4e1b4d5d5d760b\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contest_submissions\` ADD CONSTRAINT \`FK_6158d5e0abc105487bfe5a4ff9f\` FOREIGN KEY (\`submission_id\`) REFERENCES \`submissions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contest_submissions\` ADD CONSTRAINT \`FK_bc6d69c4de1d9349152bd9717de\` FOREIGN KEY (\`problem_version_id\`) REFERENCES \`problem_versions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_analytics_daily\` ADD CONSTRAINT \`FK_a84d9dc2f08c3e3ca97cd0bf3f5\` FOREIGN KEY (\`problem_id\`) REFERENCES \`problems\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` ADD CONSTRAINT \`FK_f160d97a931844109de9d04228f\` FOREIGN KEY (\`actor_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_87b8888186ca9769c960e926870\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_b23c65e50a758245a33ee35fda1\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_b23c65e50a758245a33ee35fda1\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_87b8888186ca9769c960e926870\``);
        await queryRunner.query(`ALTER TABLE \`audit_logs\` DROP FOREIGN KEY \`FK_f160d97a931844109de9d04228f\``);
        await queryRunner.query(`ALTER TABLE \`problem_analytics_daily\` DROP FOREIGN KEY \`FK_a84d9dc2f08c3e3ca97cd0bf3f5\``);
        await queryRunner.query(`ALTER TABLE \`contest_submissions\` DROP FOREIGN KEY \`FK_bc6d69c4de1d9349152bd9717de\``);
        await queryRunner.query(`ALTER TABLE \`contest_submissions\` DROP FOREIGN KEY \`FK_6158d5e0abc105487bfe5a4ff9f\``);
        await queryRunner.query(`ALTER TABLE \`contest_submissions\` DROP FOREIGN KEY \`FK_1eb6afc5d255f4e1b4d5d5d760b\``);
        await queryRunner.query(`ALTER TABLE \`contest_submissions\` DROP FOREIGN KEY \`FK_cdedd241911ab85d4810cdf6120\``);
        await queryRunner.query(`ALTER TABLE \`contests\` DROP FOREIGN KEY \`FK_9a102ffa211c38589ad61786ca7\``);
        await queryRunner.query(`ALTER TABLE \`contest_participants\` DROP FOREIGN KEY \`FK_005a4088e1f40bae55d74f48069\``);
        await queryRunner.query(`ALTER TABLE \`contest_participants\` DROP FOREIGN KEY \`FK_070b6a54501fe8b00564f612c0e\``);
        await queryRunner.query(`ALTER TABLE \`contest_problems\` DROP FOREIGN KEY \`FK_79cff0de5c2e9689c9051bfa573\``);
        await queryRunner.query(`ALTER TABLE \`contest_problems\` DROP FOREIGN KEY \`FK_2b057cbe0ad987487ad746e6ea7\``);
        await queryRunner.query(`ALTER TABLE \`discussion_threads\` DROP FOREIGN KEY \`FK_5fd7e7307b43ad51457114fecb0\``);
        await queryRunner.query(`ALTER TABLE \`discussion_threads\` DROP FOREIGN KEY \`FK_285bbbc4b69b202f169f037d0d6\``);
        await queryRunner.query(`ALTER TABLE \`discussion_posts\` DROP FOREIGN KEY \`FK_b7185cf357c3d27c3c5b80fec67\``);
        await queryRunner.query(`ALTER TABLE \`discussion_posts\` DROP FOREIGN KEY \`FK_5861d03c3859af8f7b40032ef08\``);
        await queryRunner.query(`ALTER TABLE \`discussion_posts\` DROP FOREIGN KEY \`FK_f2c4196101d6a0e8d868ad00595\``);
        await queryRunner.query(`ALTER TABLE \`discussion_posts\` DROP FOREIGN KEY \`FK_0b0950535a2571b4f375db7b4ae\``);
        await queryRunner.query(`ALTER TABLE \`post_votes\` DROP FOREIGN KEY \`FK_37fb39fa2d813582024968ef264\``);
        await queryRunner.query(`ALTER TABLE \`post_votes\` DROP FOREIGN KEY \`FK_be565a04e47c8b846f6cc7fcac6\``);
        await queryRunner.query(`ALTER TABLE \`submission_testcase_results\` DROP FOREIGN KEY \`FK_6527eff7f51c75b4a76eb0811e5\``);
        await queryRunner.query(`ALTER TABLE \`submission_testcase_results\` DROP FOREIGN KEY \`FK_c4b6a8ad3128e26008c5894de1c\``);
        await queryRunner.query(`ALTER TABLE \`submissions\` DROP FOREIGN KEY \`FK_f6da7d4c4fa4e0d9db7e5388dd1\``);
        await queryRunner.query(`ALTER TABLE \`submissions\` DROP FOREIGN KEY \`FK_2408840ce2806c5d5e072a2e9b4\``);
        await queryRunner.query(`ALTER TABLE \`submissions\` DROP FOREIGN KEY \`FK_fca12c4ddd646dea4572c6815a9\``);
        await queryRunner.query(`ALTER TABLE \`judge_jobs\` DROP FOREIGN KEY \`FK_f7bc8317fbd6d64e81c82d4cd10\``);
        await queryRunner.query(`ALTER TABLE \`code_runs\` DROP FOREIGN KEY \`FK_0b1d0cf3df0e3d497fd5bcff7d3\``);
        await queryRunner.query(`ALTER TABLE \`code_runs\` DROP FOREIGN KEY \`FK_d07e1f5cb7df8f117fe6eeade7d\``);
        await queryRunner.query(`ALTER TABLE \`code_runs\` DROP FOREIGN KEY \`FK_7d8b87357119fe38371ec1e4936\``);
        await queryRunner.query(`ALTER TABLE \`code_drafts\` DROP FOREIGN KEY \`FK_82863e10839b30ece57ef27344a\``);
        await queryRunner.query(`ALTER TABLE \`code_drafts\` DROP FOREIGN KEY \`FK_7779820de4c13efd6ddcd8fcf01\``);
        await queryRunner.query(`ALTER TABLE \`code_drafts\` DROP FOREIGN KEY \`FK_ab119cc7cddc270aa1bde7a118f\``);
        await queryRunner.query(`ALTER TABLE \`user_problem_stats\` DROP FOREIGN KEY \`FK_34f4955f05e2bfaee8969b7d2ae\``);
        await queryRunner.query(`ALTER TABLE \`user_problem_stats\` DROP FOREIGN KEY \`FK_01ff3887bfd3528d8e61904cfdb\``);
        await queryRunner.query(`ALTER TABLE \`user_skills\` DROP FOREIGN KEY \`FK_eb69710b0a00f42fb95fc2ac2f5\``);
        await queryRunner.query(`ALTER TABLE \`user_skills\` DROP FOREIGN KEY \`FK_6926002c360291df66bb2c5fdeb\``);
        await queryRunner.query(`ALTER TABLE \`user_badges\` DROP FOREIGN KEY \`FK_715b81e610ab276ff6603cfc8e8\``);
        await queryRunner.query(`ALTER TABLE \`user_badges\` DROP FOREIGN KEY \`FK_f1221d9b1aaa64b1f3c98ed46d3\``);
        await queryRunner.query(`ALTER TABLE \`problem_checkers\` DROP FOREIGN KEY \`FK_380eb75ea1990d3f31dd0e0be96\``);
        await queryRunner.query(`ALTER TABLE \`problem_checkers\` DROP FOREIGN KEY \`FK_cee7a29419bc1301bec1699bf62\``);
        await queryRunner.query(`ALTER TABLE \`problem_versions\` DROP FOREIGN KEY \`FK_87a7910747c4da573295fea59d1\``);
        await queryRunner.query(`ALTER TABLE \`problem_versions\` DROP FOREIGN KEY \`FK_cf1ddcf55381e40759f46e0087d\``);
        await queryRunner.query(`ALTER TABLE \`problems\` DROP FOREIGN KEY \`FK_2aee58a468d036cc139963ae789\``);
        await queryRunner.query(`ALTER TABLE \`problem_tags\` DROP FOREIGN KEY \`FK_853473f54d7b1e91b236346fa13\``);
        await queryRunner.query(`ALTER TABLE \`problem_tags\` DROP FOREIGN KEY \`FK_e369a453fb95b878301184caddc\``);
        await queryRunner.query(`ALTER TABLE \`problem_companies\` DROP FOREIGN KEY \`FK_ec1e9bbb0e351a047bd25b3b8cc\``);
        await queryRunner.query(`ALTER TABLE \`problem_companies\` DROP FOREIGN KEY \`FK_36f3b2eb80862d2d435920f8d6c\``);
        await queryRunner.query(`ALTER TABLE \`problem_topics\` DROP FOREIGN KEY \`FK_b3c36df89b28f1046fdfd739e43\``);
        await queryRunner.query(`ALTER TABLE \`problem_topics\` DROP FOREIGN KEY \`FK_04c2262bcf0279527e7c1ce7ac0\``);
        await queryRunner.query(`ALTER TABLE \`user_profiles\` DROP FOREIGN KEY \`FK_6ca9503d77ae39b4b5a6cc3ba88\``);
        await queryRunner.query(`ALTER TABLE \`user_sessions\` DROP FOREIGN KEY \`FK_e9658e959c490b0a634dfc54783\``);
        await queryRunner.query(`ALTER TABLE \`user_oauth_accounts\` DROP FOREIGN KEY \`FK_7eb25183e951b6ca44f292df21a\``);
        await queryRunner.query(`ALTER TABLE \`user_oauth_accounts\` DROP FOREIGN KEY \`FK_a093a39110ecd3602d87f0e814b\``);
        await queryRunner.query(`ALTER TABLE \`password_reset_tokens\` DROP FOREIGN KEY \`FK_52ac39dd8a28730c63aeb428c9c\``);
        await queryRunner.query(`ALTER TABLE \`problem_statements\` DROP FOREIGN KEY \`FK_4908bdeec65b3df8556b12cb307\``);
        await queryRunner.query(`ALTER TABLE \`problem_statements\` DROP FOREIGN KEY \`FK_6b83ed82bb1eb4085aa8d3a01a5\``);
        await queryRunner.query(`ALTER TABLE \`problem_examples\` DROP FOREIGN KEY \`FK_dcba451585d017a79af3441b974\``);
        await queryRunner.query(`ALTER TABLE \`problem_hints\` DROP FOREIGN KEY \`FK_63bfc34bae0e97ed6a7455ce693\``);
        await queryRunner.query(`ALTER TABLE \`test_groups\` DROP FOREIGN KEY \`FK_70ead889490b83882a744ecff97\``);
        await queryRunner.query(`ALTER TABLE \`test_cases\` DROP FOREIGN KEY \`FK_d8c857a3c73908c4e8dbd5125f8\``);
        await queryRunner.query(`DROP INDEX \`IDX_b23c65e50a758245a33ee35fda\` ON \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_87b8888186ca9769c960e92687\` ON \`user_roles\``);
        await queryRunner.query(`DROP TABLE \`user_roles\``);
        await queryRunner.query(`DROP TABLE \`audit_logs\``);
        await queryRunner.query(`DROP TABLE \`problem_analytics_daily\``);
        await queryRunner.query(`DROP TABLE \`contest_submissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_b4731dd3cabd0b2386b443e2e6\` ON \`contests\``);
        await queryRunner.query(`DROP TABLE \`contests\``);
        await queryRunner.query(`DROP TABLE \`contest_participants\``);
        await queryRunner.query(`DROP TABLE \`contest_problems\``);
        await queryRunner.query(`DROP TABLE \`discussion_threads\``);
        await queryRunner.query(`DROP INDEX \`idx_thread_time\` ON \`discussion_posts\``);
        await queryRunner.query(`DROP TABLE \`discussion_posts\``);
        await queryRunner.query(`DROP TABLE \`post_votes\``);
        await queryRunner.query(`DROP INDEX \`IDX_201cd5b8bd6e678a05de0aafe2\` ON \`submission_testcase_results\``);
        await queryRunner.query(`DROP TABLE \`submission_testcase_results\``);
        await queryRunner.query(`DROP INDEX \`idx_submissions_user\` ON \`submissions\``);
        await queryRunner.query(`DROP INDEX \`idx_submissions_problem\` ON \`submissions\``);
        await queryRunner.query(`DROP TABLE \`submissions\``);
        await queryRunner.query(`DROP TABLE \`judge_jobs\``);
        await queryRunner.query(`DROP INDEX \`IDX_b27c191484858fdadc253e8828\` ON \`programming_languages\``);
        await queryRunner.query(`DROP TABLE \`programming_languages\``);
        await queryRunner.query(`DROP TABLE \`code_runs\``);
        await queryRunner.query(`DROP INDEX \`IDX_bfb5b81c1911e9be2b198594df\` ON \`code_drafts\``);
        await queryRunner.query(`DROP TABLE \`code_drafts\``);
        await queryRunner.query(`DROP TABLE \`user_problem_stats\``);
        await queryRunner.query(`DROP TABLE \`user_skills\``);
        await queryRunner.query(`DROP INDEX \`IDX_81f05095507fd84aa2769b4a52\` ON \`skills\``);
        await queryRunner.query(`DROP TABLE \`skills\``);
        await queryRunner.query(`DROP TABLE \`user_badges\``);
        await queryRunner.query(`DROP INDEX \`IDX_48fe47e292737e09162b08c4f7\` ON \`badges\``);
        await queryRunner.query(`DROP TABLE \`badges\``);
        await queryRunner.query(`DROP INDEX \`IDX_7397752718d1c9eb873722ec9b\` ON \`languages\``);
        await queryRunner.query(`DROP TABLE \`languages\``);
        await queryRunner.query(`DROP TABLE \`problem_checkers\``);
        await queryRunner.query(`DROP INDEX \`IDX_78886d6bb133f882cd17cf0ae0\` ON \`problem_versions\``);
        await queryRunner.query(`DROP TABLE \`problem_versions\``);
        await queryRunner.query(`DROP INDEX \`IDX_92cf8d938405ef6369f311f0c4\` ON \`problems\``);
        await queryRunner.query(`DROP TABLE \`problems\``);
        await queryRunner.query(`DROP TABLE \`problem_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_b3aa10c29ea4e61a830362bd25\` ON \`tags\``);
        await queryRunner.query(`DROP TABLE \`tags\``);
        await queryRunner.query(`DROP TABLE \`problem_companies\``);
        await queryRunner.query(`DROP INDEX \`IDX_b28b07d25e4324eee577de5496\` ON \`companies\``);
        await queryRunner.query(`DROP TABLE \`companies\``);
        await queryRunner.query(`DROP TABLE \`problem_topics\``);
        await queryRunner.query(`DROP INDEX \`IDX_97c66ab0029f49fde30517f819\` ON \`topics\``);
        await queryRunner.query(`DROP TABLE \`topics\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`user_profiles\``);
        await queryRunner.query(`DROP INDEX \`IDX_f6d54f95c31b73fb1bdd8e91d0\` ON \`roles\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP INDEX \`idx_user_sessions_user\` ON \`user_sessions\``);
        await queryRunner.query(`DROP TABLE \`user_sessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_826b133c0546f9b9cd118b4948\` ON \`user_oauth_accounts\``);
        await queryRunner.query(`DROP TABLE \`user_oauth_accounts\``);
        await queryRunner.query(`DROP INDEX \`IDX_edb8eb7b21dfcf168d3e2fd5ea\` ON \`oauth_providers\``);
        await queryRunner.query(`DROP TABLE \`oauth_providers\``);
        await queryRunner.query(`DROP TABLE \`password_reset_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_5d115f32b62761364140215c20\` ON \`problem_statements\``);
        await queryRunner.query(`DROP TABLE \`problem_statements\``);
        await queryRunner.query(`DROP TABLE \`problem_examples\``);
        await queryRunner.query(`DROP INDEX \`IDX_ae435edbf4bc54895757ad0c05\` ON \`problem_hints\``);
        await queryRunner.query(`DROP TABLE \`problem_hints\``);
        await queryRunner.query(`DROP TABLE \`test_groups\``);
        await queryRunner.query(`DROP TABLE \`test_cases\``);
    }

}
