import { MigrationInterface, QueryRunner } from "typeorm";

export class OptimizeEntitiesWithIndexesForQueryPerformance1766510078853 implements MigrationInterface {
    name = 'OptimizeEntitiesWithIndexesForQueryPerformance1766510078853'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`problem_topics\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`problem_companies\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`problem_tags\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user_skills\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user_skills\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contest_problems\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user_skills\` CHANGE \`level\` \`level\` tinyint UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`user_skills\` CHANGE \`years\` \`years\` tinyint UNSIGNED NULL`);
        await queryRunner.query(`CREATE INDEX \`idx_problem_topics_topic\` ON \`problem_topics\` (\`topic_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_problem_topics_problem\` ON \`problem_topics\` (\`problem_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_problem_companies_company\` ON \`problem_companies\` (\`company_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_problem_companies_problem\` ON \`problem_companies\` (\`problem_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_problem_tags_tag\` ON \`problem_tags\` (\`tag_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_problem_tags_problem\` ON \`problem_tags\` (\`problem_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_languages_code\` ON \`languages\` (\`code\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_user_problem_stats_last_attempt\` ON \`user_problem_stats\` (\`last_attempt_at\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_user_problem_stats_status\` ON \`user_problem_stats\` (\`bestStatus\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_user_problem_stats_user\` ON \`user_problem_stats\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_badges_code\` ON \`badges\` (\`code\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_user_badges_badge\` ON \`user_badges\` (\`badge_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_user_badges_user\` ON \`user_badges\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_user_skills_user\` ON \`user_skills\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_user_skills_skill\` ON \`user_skills\` (\`skill_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_code_drafts_problem\` ON \`code_drafts\` (\`problem_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_code_drafts_user\` ON \`code_drafts\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_code_runs_problem\` ON \`code_runs\` (\`problem_version_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_code_runs_status\` ON \`code_runs\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_code_runs_user\` ON \`code_runs\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_programming_languages_enabled\` ON \`programming_languages\` (\`isEnabled\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_programming_languages_code\` ON \`programming_languages\` (\`code\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_submission_testcase_status\` ON \`submission_testcase_results\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_judge_jobs_worker\` ON \`judge_jobs\` (\`worker_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_judge_jobs_status\` ON \`judge_jobs\` (\`queueStatus\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_judge_jobs_submission\` ON \`judge_jobs\` (\`submission_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_submissions_language\` ON \`submissions\` (\`language_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_submissions_status\` ON \`submissions\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_discussion_threads_created_at\` ON \`discussion_threads\` (\`created_at\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_discussion_threads_created_by\` ON \`discussion_threads\` (\`created_by\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_discussion_threads_problem\` ON \`discussion_threads\` (\`problem_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_discussion_posts_best\` ON \`discussion_posts\` (\`is_best_solution\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_discussion_posts_type\` ON \`discussion_posts\` (\`postType\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_discussion_posts_parent\` ON \`discussion_posts\` (\`parent_post_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_discussion_posts_author\` ON \`discussion_posts\` (\`author_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_post_votes_user\` ON \`post_votes\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_post_votes_post\` ON \`post_votes\` (\`post_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_contest_problems_problem\` ON \`contest_problems\` (\`problem_version_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_contest_problems_contest\` ON \`contest_problems\` (\`contest_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_contest_participants_user\` ON \`contest_participants\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_contest_participants_contest\` ON \`contest_participants\` (\`contest_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_contests_type\` ON \`contests\` (\`type\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_contests_start_end\` ON \`contests\` (\`start_at\`, \`end_at\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_contests_code\` ON \`contests\` (\`code\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_contest_submissions_submission\` ON \`contest_submissions\` (\`submission_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_contest_submissions_user\` ON \`contest_submissions\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_contest_submissions_contest\` ON \`contest_submissions\` (\`contest_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_problem_analytics_date\` ON \`problem_analytics_daily\` (\`date\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_audit_logs_created_at\` ON \`audit_logs\` (\`created_at\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_audit_logs_target\` ON \`audit_logs\` (\`target_type\`, \`target_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_audit_logs_action\` ON \`audit_logs\` (\`action\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_audit_logs_actor\` ON \`audit_logs\` (\`actor_user_id\`)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`idx_audit_logs_actor\` ON \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`idx_audit_logs_action\` ON \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`idx_audit_logs_target\` ON \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`idx_audit_logs_created_at\` ON \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`idx_problem_analytics_date\` ON \`problem_analytics_daily\``);
        await queryRunner.query(`DROP INDEX \`idx_contest_submissions_contest\` ON \`contest_submissions\``);
        await queryRunner.query(`DROP INDEX \`idx_contest_submissions_user\` ON \`contest_submissions\``);
        await queryRunner.query(`DROP INDEX \`idx_contest_submissions_submission\` ON \`contest_submissions\``);
        await queryRunner.query(`DROP INDEX \`idx_contests_code\` ON \`contests\``);
        await queryRunner.query(`DROP INDEX \`idx_contests_start_end\` ON \`contests\``);
        await queryRunner.query(`DROP INDEX \`idx_contests_type\` ON \`contests\``);
        await queryRunner.query(`DROP INDEX \`idx_contest_participants_contest\` ON \`contest_participants\``);
        await queryRunner.query(`DROP INDEX \`idx_contest_participants_user\` ON \`contest_participants\``);
        await queryRunner.query(`DROP INDEX \`idx_contest_problems_contest\` ON \`contest_problems\``);
        await queryRunner.query(`DROP INDEX \`idx_contest_problems_problem\` ON \`contest_problems\``);
        await queryRunner.query(`DROP INDEX \`idx_post_votes_post\` ON \`post_votes\``);
        await queryRunner.query(`DROP INDEX \`idx_post_votes_user\` ON \`post_votes\``);
        await queryRunner.query(`DROP INDEX \`idx_discussion_posts_author\` ON \`discussion_posts\``);
        await queryRunner.query(`DROP INDEX \`idx_discussion_posts_parent\` ON \`discussion_posts\``);
        await queryRunner.query(`DROP INDEX \`idx_discussion_posts_type\` ON \`discussion_posts\``);
        await queryRunner.query(`DROP INDEX \`idx_discussion_posts_best\` ON \`discussion_posts\``);
        await queryRunner.query(`DROP INDEX \`idx_discussion_threads_problem\` ON \`discussion_threads\``);
        await queryRunner.query(`DROP INDEX \`idx_discussion_threads_created_by\` ON \`discussion_threads\``);
        await queryRunner.query(`DROP INDEX \`idx_discussion_threads_created_at\` ON \`discussion_threads\``);
        await queryRunner.query(`DROP INDEX \`idx_submissions_status\` ON \`submissions\``);
        await queryRunner.query(`DROP INDEX \`idx_submissions_language\` ON \`submissions\``);
        await queryRunner.query(`DROP INDEX \`idx_judge_jobs_submission\` ON \`judge_jobs\``);
        await queryRunner.query(`DROP INDEX \`idx_judge_jobs_status\` ON \`judge_jobs\``);
        await queryRunner.query(`DROP INDEX \`idx_judge_jobs_worker\` ON \`judge_jobs\``);
        await queryRunner.query(`DROP INDEX \`idx_submission_testcase_status\` ON \`submission_testcase_results\``);
        await queryRunner.query(`DROP INDEX \`idx_programming_languages_code\` ON \`programming_languages\``);
        await queryRunner.query(`DROP INDEX \`idx_programming_languages_enabled\` ON \`programming_languages\``);
        await queryRunner.query(`DROP INDEX \`idx_code_runs_user\` ON \`code_runs\``);
        await queryRunner.query(`DROP INDEX \`idx_code_runs_status\` ON \`code_runs\``);
        await queryRunner.query(`DROP INDEX \`idx_code_runs_problem\` ON \`code_runs\``);
        await queryRunner.query(`DROP INDEX \`idx_code_drafts_user\` ON \`code_drafts\``);
        await queryRunner.query(`DROP INDEX \`idx_code_drafts_problem\` ON \`code_drafts\``);
        await queryRunner.query(`DROP INDEX \`idx_user_skills_skill\` ON \`user_skills\``);
        await queryRunner.query(`DROP INDEX \`idx_user_skills_user\` ON \`user_skills\``);
        await queryRunner.query(`DROP INDEX \`idx_user_badges_user\` ON \`user_badges\``);
        await queryRunner.query(`DROP INDEX \`idx_user_badges_badge\` ON \`user_badges\``);
        await queryRunner.query(`DROP INDEX \`idx_badges_code\` ON \`badges\``);
        await queryRunner.query(`DROP INDEX \`idx_user_problem_stats_user\` ON \`user_problem_stats\``);
        await queryRunner.query(`DROP INDEX \`idx_user_problem_stats_status\` ON \`user_problem_stats\``);
        await queryRunner.query(`DROP INDEX \`idx_user_problem_stats_last_attempt\` ON \`user_problem_stats\``);
        await queryRunner.query(`DROP INDEX \`idx_languages_code\` ON \`languages\``);
        await queryRunner.query(`DROP INDEX \`idx_problem_tags_problem\` ON \`problem_tags\``);
        await queryRunner.query(`DROP INDEX \`idx_problem_tags_tag\` ON \`problem_tags\``);
        await queryRunner.query(`DROP INDEX \`idx_problem_companies_problem\` ON \`problem_companies\``);
        await queryRunner.query(`DROP INDEX \`idx_problem_companies_company\` ON \`problem_companies\``);
        await queryRunner.query(`DROP INDEX \`idx_problem_topics_problem\` ON \`problem_topics\``);
        await queryRunner.query(`DROP INDEX \`idx_problem_topics_topic\` ON \`problem_topics\``);
        await queryRunner.query(`ALTER TABLE \`user_skills\` CHANGE \`years\` \`years\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`user_skills\` CHANGE \`level\` \`level\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`contest_problems\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`user_skills\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`user_skills\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`problem_tags\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`problem_companies\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`problem_topics\` DROP COLUMN \`created_at\``);
    }

}
